Add page partner and fixed background color
baza-trainee/dokoopy-frontend pull request #25
Opened 2023-09-02 08:35 UTC by Oaleks262

2023-09-02 18:09 UTC, Oaleks262 commented
Подивись будь ласка і якщо треба правки зроблю

2023-09-02 19:52 UTC, AscariA10 requested changes
Я продивився весь код, є декілька питань:

1.Що це за span і чому 2 рази у спані по 4 посилання, і чому вони не списком?
Я якщо чесно не зрозумів цей компонент, можеш скрін кинути як він виглядає?
2. В мене прохання не використовувати вкладені селектори, постарайся будь ласка переписати через классові, і використовувати тільки классові, так простіше підтримувати проект

2023-09-04 12:57 UTC, Oaleks262 commented
Було відредаговано

2023-09-04 13:33 UTC, Oaleks262 commented
fixed

2023-09-05 15:11 UTC, AscariA10 approved these changes
Приймаю. Якщо знацду недоліки по ходу то вкажу в переписці.
Багато зробив, дякую)

2023-09-05 15:11 UTC, merged