our project adaptive
baza-trainee/dokoopy-frontend pull request #36
Opened 2023-09-06 11:36 UTC by Olenakas

2023-09-06 12:32 UTC, AscariA10 commented on src/styles/components/_projects.scss
> +@media (min-width: 390px) {
Не зовсім розумію точки переходу. 390 не прописана, як і 1440.

2023-09-06 12:37 UTC, AscariA10 requested changes
Будь-ласка синхронізуй розміри контейнера загального та своєї секції. В нас ніде не прописана точа 390px та 1440 px.

2023-09-06 13:14 UTC, Olenakas commented on src/styles/components/_projects.scss
> +@media (min-width: 390px) {
Я робила по макету: 1440px, 768px, 390px

2023-09-06 20:24 UTC, Olenakas commented
Виправила на точки перелому: 1280px, 768px, 480px. До 480px верстка гумова.

2023-09-07 17:25 UTC, AscariA10 approved these changes

2023-09-07 17:25 UTC, merged